### ISSUE TITLE
Subscribe Flow - Fee Recipient Check: If check is positive why are we showing him the 

### ISSUE THREAD

**Issue by Pol-Lanski** [GeneralMagicio/dappnode-mev-smoothing-pool#47]
Firstly, a strange scrollable box appears next to the validator and the Fee Recipient

![Screenshot 2023-05-05 at 18 25 02](https://user-images.githubusercontent.com/19168735/236500726-b8d824d3-c810-44ae-8555-debd11a4d637.png)

Secondly, if the Fee Recipient check is positive, we shouldn't show the same address twice. We should say: "Great, your Fee Recipient is already set to the MEV Smoothing Pool!" instead of the 2nd one.

Looking for Tosin's opinion here.

**Comment by alrevuelta** [comment]
Related: can we have a link of the validator to beaconchain website? [0xb69ad](https://prater.beaconcha.in/validator/217668). Displaying the index instead of the full key might be more visual, but @Pol-Lanski decission.

Example:
Your Validator:
[217668](https://prater.beaconcha.in/validator/217668)

**Comment by alrevuelta** [comment]
Perhaps we can also merge "Fee recipient" and "Check MEV boost", both look the same for me.
