### ISSUE TITLE
Subscribe/Unsubribe dont allow the user to exit

### ISSUE THREAD

**Issue by alrevuelta** [GeneralMagicio/dappnode-mev-smoothing-pool#61]
When subscribing or unsubscribing, there are a couple of problems that can cause the user to subscribe/unsubscribe twice, since the information has not been updated:
* The user shall not be able to close (x) the window until the tx is validated. Otherwise the user can send the tx, close the window and it can call sub/unsub again and again on the same validator. Both for subscribe and unsubscribe.
* Once the tx is validated, wait some more time to ensure the tx has been propagated to all the nodes and the new state reflects the new reality. I would use confirmations. 2 confirmations is fine.
* Not sure if already done, but refresh the website once thats done, right after 2 confirmations are sent

![image](https://github.com/GeneralMagicio/dappnode-mev-smoothing-pool/assets/8811422/582786aa-5960-48fc-993f-82b1803d11f8)

**Comment by marthendalnunes** [comment]
@alrevuelta I understand the issue, but that's not an issue with the frontend, but rather with the backend/contracts infrastructure. It doesn't solve the problem to remove the close modal button, since the user can simply reload the page or open a new tab and subscribe again, any measure we take at the frontend will not solve the problem (you can check any dapp that provides something like that and the lock is never on the frontend). Ideally the contract should throw an error if the user is making a wrong action (subscribing/unsubscribing twice)

**Comment by marthendalnunes** [comment]
Although I agree on refetching the data after 2 confirmations, I'll apply this change

**Comment by alrevuelta** [comment]
> since the user can simply reload the page or open a new tab and subscribe again

good point. Well lets wait 2 confirmations and dont allow to close (x) while the tx is pending. We wont be protected 100% but it should most of the cases.


>  Ideally the contract should throw an error if the user is making a wrong action (subscribing/unsubscribing twice)

Long story but since everything is event-based (contract just triggers events without knowing anything) unfortunately thats not possible

**Comment by marthendalnunes** [comment]
that's fine, I'll apply the changes
